name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: |
          cp apps/daimo-web/.env.example apps/daimo-web/.env
          cp packages/daimo-api/.env.example packages/daimo-api/.env
          npm ci
          npm test

  test-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - env:
          BASE_MAINNET_RPC: ${{ secrets.BASE_MAINNET_RPC }}
        run: |
          forge test -vvv --fork-url "$BASE_MAINNET_RPC" --no-match-path "test/uniswap/*"
          forge test -vvv --fork-url "$BASE_MAINNET_RPC" --fork-block-number 14513720 --match-path "test/uniswap/*"
          git diff --exit-code
        # forge test -vvv --fork-url "$BASE_MAINNET_RPC" --fork-block-number 15950101 --match-path "test/uniswap/*" vivek swap
        working-directory: ./packages/contract

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: |
          npm ci
          npm run lint && npm run codegen
        # Re-enable once Wagmi fixes their bug: git diff --exit-code
        # https://github.com/wevm/wagmi/issues/2528
