name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - run: |
          cp apps/daimo-web/.env.example apps/daimo-web/.env
          cp packages/daimo-api/.env.example packages/daimo-api/.env
          npm ci
          NODE_OPTIONS='--max-old-space-size=4096' npm test

  test-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - env:
          BASE_MAINNET_RPC: ${{ vars.BASE_MAINNET_RPC }}
        run: |
          echo Using RPC $BASE_MAINNET_RPC
          forge build --extra-output-files metadata
          echo SOURCE
          git status
          git submodule foreach --recursive 'git rev-parse HEAD'
          find src -type f -exec shasum {} + | sort
          echo TOOLCHAIN
          forge --version
          echo COMPILED OUTPUT
          grep . out/*/*.metadata.json
          sudo apt-get install -y jq
          cat out/DaimoAccountV2.sol/DaimoAccountV2.json | jq .bytecode | fold -w 80
          cat out/DaimoAccountV2.sol/DaimoAccountV2.json | jq .bytecode | shasum
          echo TEST
          forge test -vvv --fork-url "$BASE_MAINNET_RPC" --no-match-path "test/uniswap/*"
          forge test -vvv --fork-url "$BASE_MAINNET_RPC" --fork-block-number 14513720 --match-path "test/uniswap/*" --no-match-path "test/uniswap/Quoter.t.sol"
          forge test -vvv --fork-url "$BASE_MAINNET_RPC" --fork-block-number 15950101 --match-path "test/uniswap/Quoter.t.sol"
          cd ../.. && npm ci && npm run codegen
          git diff --exit-code
        working-directory: ./packages/contract

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: |
          npm ci
          npm run lint
